# Generated by Django 5.2.8 on 2025-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='fields',
        ),
        migrations.AddField(
            model_name='question',
            name='fields',
            field=models.ManyToManyField(to='it_test.field'),
        ),
    ]
