# Generated by Django 5.2.8 on 2025-11-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_test', '0003_alter_field_name_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='fields',
            field=models.ManyToManyField(related_name='questions', to='it_test.field'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
